id = "mcp-server-linear"
name = "Linear MCP Server"
description = "Model Context Protocol Server for Linear"
version = "0.1.0"
schema_version = 1
authors = ["Jeffrey Guenther <guenther.jeffrey@gmail.com>"]
repository = "https://github.com/LoamStudios/zed-mcp-server-linear"

[context_servers.mcp-server-linear]
name = "Linear MCP Server"
